base:
  build: .

package:
  image: biofoam_base
  # volumes_from:
  #   - data
  env_file: ./.env
  # command: package
  # entrypoint: ls
  entrypoint: /bin/bash

# start:
#   image: biofoam_base
#   volumes_from:
#     - data
#   env_file: ./.env
#   ports:
#     - "3000:3000"
#   command: dev

data:
  image: biofoam_base
  volumes:
    - ./:/biofoam
