dev:
  build: .
  volumes_from:
    - data
  ports:
    - "49300:3000"

data:
  image: busybox
  volumes:
    - ./_src/:/biofoam/_src
    - ./vendor/:/biofoam/vendor
    - ./gulp/:/biofoam/gulp
  entrypoint: true
