dev:
  build: .
  volumes_from:
    - data
  ports:
    - "49300:3000"
  # entrypoint: bash

data:
  image: busybox
  volumes:
    - ./_src/:/biofoam/_src
    - ./vendor/:/biofoam/vendor
    - ./gulp/:/biofoam/gulp
    - ./_dist/:/biofoam/_dist
  entrypoint: true
